server:
    port: 8888
    servlet:
        context-path: /duscrumtool
spring:
    datasource:
        url: jdbc:h2:mem:testdb
    h2:
        console:
            enabled: true
    jpa:
        hibernate:
            ddl-auto: update
